layashop/layashop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('shop.urls',namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

layashop/shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns =[

    path('', views.home_page, name='home_page'),
    path('list.html', views.product_list, name='product_list'),
    path('about.html', views.about_page, name='about'),
    path('contact.html', views.contact_page, name='contact'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

layashop/shop/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)
    image = models.ImageField(upload_to='products/%y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug',),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

layashop/shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product


# Create your views here.

def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)

    return render(request, 'shop/product/list.html', {'categories':categories, 'products': products})

def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id,slug=slug,available=True)
    return render(request, 'shop/product/detail.html', {'product':product})

def home_page(request):
    return render(request,'shop/product/home.html',{})

def about_page(request):
    return render(request,'shop/product/about.html',{})

def contact_page(request):
    return render(request,'shop/product/contact.html',{})

layashop/shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Laya's Clothing{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=DynaPuff&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;400&display=swap" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet" />
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand heading" href="#">Lambda Clothing</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">

            <a href="{% url "shop:home_page" %}" class="nav-link active" aria-current="page">Home</a>
        </li>
           <li class="nav-item">
          <a class="nav-link active" href="{% url "shop:about" %}" aria-current="page">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url "shop:product_list" %}"  aria-current="page">Products</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url "shop:contact" %}"   aria-current="page">Contact</a>
        </li>

      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

    <div id="subheader">

        <div class="cart">
            <a href="#"><i class="fa fa-shopping-cart" style="font-size:36px"></i></a>

        </div>
    </div>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
    <footer class="bg-dark">
     <div class="row">
         <div class="col-12 col-md-6 "><h5>Lambda Clothing</h5>
             <div class="icon">
                 <a href="https://twitter.com/Gaya86229157"><i class="fa fa-fw fa-twitter"></i></a></div>
                 <div class="icon">
             <a href="https://youtube.com"><i class="fa fa-fw fa-youtube"></i></a></div>
                 <div class="icon"><a href="https://instagram.com/lambda_clothing_india?igshid=Y2ZmNzg0YzQ="><i class="fa fa-fw fa-instagram"></i></a></div>
            <div class="icon"> <a href="https://www.facebook.com/balaji.ash.1"><i class="fa fa-fw fa-facebook"></i></a></div>

         </div>

         <div class="col-12 col-md-6"><h5>Contact Us</h5>
         <div style="color: #77b6e2">
             <hr>
             <p>1230 Berkshire Drive,</p>
             <p>Williamston,</p>
             <p>Michigan</p>
             <p>48895, USA</p>
         </div></div>
     </div>
        <div class="row">
            <p style="font-size: 12px; text-align: center; color:aqua;">&copy; 2022 Lambda Clothing</p>
        </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB41DRUbKWJHPxaFjMAwdrzWzbVKartNGg&callback=initMap&v=weekly" defer></script>
</body>
</html>

layashop/shop/templates/shop/product/about.html
{% extends "shop/base.html" %}
{% load static %}

{% block content  %}
<div class="container mt-5 mb-5">
    <div class="row">
        <div class="col-12 col-md-6">
            <h5 class="head">ABout Page</h5>
            <h5 class="head">Lamdba Clothing</h5>
            <p>
            Lambda Clothing is a startup clothing company. Balaji is an entrepreneur and animation artist, works for leading
            gaming company in the US. He got his fashion idea from him mom who worked in the apparel industry more than 25 years.
            He designs his own prints and closely followup with factory for the production.

            </p>
        </div>
        <div class="col-12 col-md-6">
            <div class="container">
            <img src="{% static "img/IMG_3579.JPG" %}" width="60%" alt="Balaji"></div>
        </div>
    </div>

    </div>
  {% endblock %}

layashop/shop/templates/shop/product/contact.html
{% extends "shop/base.html" %}
{% load static %}

{% block content  %}
<div class="container mt-5 mb-5">
    <div class="row" id="map">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d11733.467177514327!2d-84.29427895731402!3d42.6747720666707!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8822df71869199e7%3A0xdef76fa923280c0e!2s1230%20Berkshire%20Dr%2C%20Williamston%2C%20MI%2048895!5e0!3m2!1sen!2sus!4v1661306769599!5m2!1sen!2sus" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
    </div>

    </div>
  {% endblock %}

layashop/shop/templates/shop/product/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

layashop/shop/templates/shop/product/home.html
{% extends "shop/base.html" %}
{% load static %}

{% block content  %}
<div class="container mt-5 mb-5">
    <div class="row">
        <div class="col-12 col-md-6">
            <h5 class="head">Lamdba Clothing</h5>
            <p>
            Lambda Clothing is a startup clothing company. Balaji is an entrepreneur and animation artist, works for leading
            gaming company in the US. He got his fashion idea from him mom who worked in the apparel industry more than 25 years.
            He designs his own prints and closely followup with factory for the production.

            </p>
        </div>
        <div class="col-12 col-md-6">
            <div class="container">
            <img src="{% static "img/IMG_3579.JPG" %}" width="60%" alt="Balaji"></div>
        </div>
    </div>

    </div>
  {% endblock %}

layashop/shop/templates/shop/product/list.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
    {% if category %}{{ category.name }}{% else %}Product{% endif %}
{% endblock %}

{% block content  %}
    <div id="sidebar">
    <h3>Categories</h3>
    <ul>
        <li {% if not category %}class="selected"{% endif %}>
            <a href="{% url 'shop:product_list' %}">All</a>
        </li>
        {% for c in categories %}
            <li {% if category.slug == c.slug %}class="selected"{% endif %}>
                <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
            </li>
        {% endfor  %}
    </ul>
    </div>
    <div id="main" class="product_list">
    <h1>{% if category %}{{ category.name }}{% else %}Products{% endif %}</h1>
    {% for p in products %}
        <div class="item">
            <a href="{{ p.get_absolute_url }}">
                <img src="{% if p.image %}{{ p.image.url }}{% else %}{% static "img/no_image.png"  %}{% endif %}" width="10%">
            </a>
        <br>
            <a href="{{ p.get_absolute_url }}">{{ p.name }}</a>
        <br>
            <p>{{ p.description }}</p>
        ${{ p.price }}
        </div>
    {% endfor %}
    </div>
{% endblock %}